branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

language: node_js

node_js:
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  provider: script
  script: yarn ci:publish
  skip_cleanup: true
  on:
    tags: true
    branch: master
